version: '3'
services:
  admin_backend:
    build: .
    image: antoniopapa/admin:0.0.1
    command: 'npm start'
    ports:
      - "8002:8000"
    environment:
      USERS_MS: http://users_ms:8000
      KAFKA_CLIENT: admin-consumer
      KAFKA_BROKERS:
      KAFKA_USERNAME:
      KAFKA_PASSWORD:
      KAFKA_TOPIC: admin_topic
      DB_HOST:
      DB_PORT: 3306
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root

  admin_consumer:
    build: .
    image: antoniopapa/admin:0.0.1
    command: 'npm run consume'
    environment:
      USERS_MS: http://users_ms:8000
      KAFKA_CLIENT: admin-consumer
      KAFKA_BROKERS:
      KAFKA_USERNAME:
      KAFKA_PASSWORD:
      KAFKA_TOPIC: admin_topic
      DB_HOST:
      DB_PORT: 3306
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root

