version: '3.9'
services:
  admin_backend:
    build: .
    command: 'npm start'
    ports:
      - "8002:8000"
    environment:
      USERS_MS: http://users_ms:8000
      KAFKA_CLIENT: admin-consumer
      KAFKA_BROKERS:
      KAFKA_USERNAME:
      KAFKA_PASSWORD:
      KAFKA_TOPIC: admin_topic
      DB_HOST:
      DB_PORT: 3306
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/app
    depends_on:
      - admin_db
    networks:
      - admin
      - users

  admin_consumer:
    build: .
    command: 'npm run consume'
    depends_on:
      - admin_db
    networks:
      - admin

  admin_db:
    image: mysql:8
    #    platform: linux/x86_64 #for m1 chip macs
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - admin

networks:
  admin:
  users:
    external: true
