apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ambassador-backend
  name: ambassador-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ambassador-backend
  template:
    metadata:
      labels:
        io.kompose.service: ambassador-backend
    spec:
      containers:
        - args:
            - npm
            - start
          env:
            - name: DB_DATABASE
              value: ambassador
            - name: DB_HOST
              value:
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_BROKERS
            - name: KAFKA_CLIENT
              value: ambassador-consumer
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_PASSWORD
            - name: KAFKA_TOPIC
              value: ambassador_topic
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_USERNAME
            - name: USERS_MS
              value: http://users_ms:8000
          image: antoniopapa/ambassador:0.0.1
          name: ambassador-backend
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ambassador-consumer
  name: ambassador-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ambassador-consumer
  template:
    metadata:
      labels:
        io.kompose.service: ambassador-consumer
    spec:
      containers:
        - args:
            - npm
            - run
            - consume
          env:
            - name: DB_DATABASE
              value: ambassador
            - name: DB_HOST
              value:
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_BROKERS
            - name: KAFKA_CLIENT
              value: ambassador-consumer
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC
              value: ambassador_topic
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_USERNAME
            - name: USERS_MS
              value: http://users_ms:8000
          image: antoniopapa/ambassador:0.0.1
          name: ambassador-consumer
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ambassador-backend
  name: ambassador-backend
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 8000
  selector:
    io.kompose.service: ambassador-backend

