version: '3'
services:
  users_backend:
    build: .
    container_name: users_ms
    image: antoniopapa/users:0.0.2
    ports:
      - '8001:8000'
    environment:
      DB_HOST:
      DB_PORT: 3306
      DB_DATABASE: users
      DB_USERNAME: root
      DB_PASSWORD: root
